_schema: _schema
source: /cannon/
paths:
  uploads: uploads
  static: ''
timezone: Asia/Calcutta
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false  
    superscript: false
    heading_ids: false
    attributes: false

collections:
  pages:
    path: content/pages.json
    label: Pages
    format: json
    schema:
      title: Title
      description: Description
      content: Content
  home:
    path: src/lib/home.json
    label: Home Content
    format: json
    schema:
      title: Home Page Title
      description: Home Page Description
      js_file: hom.js   

build:
  command: "npm install && npm run build"
  output: "dist/"
